# This file will be included by the Makefile under the project directory.

FLOAT_SRC_DIR :=lib-common/FLOAT

FLOAT_O := $(FLOAT:.a=.o)
FLOAT_VFPRINTF_O := $(dir $(FLOAT))FLOAT_vfprintf.o

FLOAT_A_OBJ := $(FLOAT_O) $(FLOAT_VFPRINTF_O)

$(FLOAT): $(FLOAT_A_OBJ)
	ar r $@ $^

# TODO: complete the following rules

$(FLOAT_O): $(FLOAT_SRC_DIR)/FLOAT.c
	$(call make_command, $(CC), -m32 -O2 -fno-if-conversion -fno-builtin -I$(LIB_COMMON_DIR) -I$(LIBC_INC_DIR) -c,cc$<, $<)

$(FLOAT_VFPRINTF_O):$(FLOAT_SRC_DIR)/FLOAT_vfprintf.c
	$(call make_command, $(CC), -m32 -O2 -fno-if-conversion -fno-builtin -fno-stack-protector -D_FORTIFY_SOURCE=0 -I$(LIB_COMMON_DIR) -I$(LIBC_INC_DIR) -c,cc$<, $<)

